# Generated by Django 6.0.4 on 2026-05-14 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='medicamento')),
                ('quantity', models.CharField(max_length=100, verbose_name='cantidad')),
                ('dosage', models.CharField(max_length=150, verbose_name='como se toma')),
                ('frequency', models.CharField(max_length=150, verbose_name='frecuencia')),
                ('duration_days', models.PositiveIntegerField(verbose_name='duracion en dias')),
                ('instructions', models.CharField(blank=True, max_length=255, verbose_name='indicaciones adicionales')),
            ],
            options={
                'verbose_name': 'Medicamento recetado',
                'verbose_name_plural': 'Medicamentos recetados',
            },
        ),
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(verbose_name='sintomas')),
                ('vital_signs', models.TextField(verbose_name='signos vitales')),
                ('diagnosis', models.TextField(blank=True, verbose_name='diagnostico')),
                ('notes', models.TextField(blank=True, verbose_name='notas adicionales')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_record', to='citas.appointment')),
            ],
            options={
                'verbose_name': 'Cardex clinico',
                'verbose_name_plural': 'Cardex clinicos',
            },
        ),
    ]
