# Generated by Django 6.0.4 on 2026-05-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_specialties'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='office_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='ubicacion del consultorio'),
        ),
        migrations.AddField(
            model_name='user',
            name='office_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='nombre del consultorio'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.URLField(blank=True, verbose_name='foto del medico'),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_license',
            field=models.CharField(blank=True, max_length=80, verbose_name='cedula profesional'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_bio',
            field=models.TextField(blank=True, verbose_name='descripcion profesional'),
        ),
    ]
