# Generated by Django 6.0.4 on 2026-05-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_office_address_user_office_name_user_photo_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='foto del medico'),
        ),
    ]
