server {
    server_name agenda.tu-dominio.com;

    client_max_body_size 20M;

    location /static/ {
        alias /srv/www/agenda/app/staticfiles/;
    }

    location /media/ {
        alias /srv/www/agenda/app/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn/agenda.sock;
    }
}