# Generated by Django 6.0.4 on 2026-05-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_cancellation_reason',
            field=models.TextField(blank=True),
        ),
    ]